project/core/views.py
# coding: utf8
from flask import Flask,request,render_template,Blueprint,redirect,flash,url_for
from werkzeug.security import check_password_hash
import pandas as pd
import os
from project.core.models import Crpage
from project.collection.mail import Emailmodule
from project.library.forms import MailForm,MailFormd
from project.models import NocMail
from project import db

core = Blueprint('core',__name__)

@core.route('/')          #首页
def index():
    return render_template('index.html')

@core.route('/croom',methods=['GET','POST'])  #IDC管理页面
def croom():
    d = Crpage('D:\\virtualenv\\ven-flask\\data\\idccr.xlsx')
    return render_template('croom.html',
                           xlsdb_columns=d.xlsdb_columns(),#读取表头
                           readxls=d.readxls(),#获取当前xlsx所有行内容
                           device_count=d.dev_count(),#读取当前所有设备数量
                           crsum=d.crsum()#获取当前所有机房
                          )
@core.route('/croompage')  #设备页面
def croompage():
    d = Crpage('D:\\virtualenv\\ven-flask\\data\\idccr.xlsx')
    xlsdb_columns = d.xlsdb_columns()
    readxls = d.readxls()
    if request.method == 'GET':
        mangeip = request.args.get('mangeip')
        crdev = request.args.get('crdev')
    return render_template('croompage.html',xlsdb_columns=xlsdb_columns,readxls=readxls,
                            mangeip=mangeip,crdev=int(crdev))

@core.route('/nocsetting',methods=['GET','POST'])
def nocsetting():
    formd = MailFormd()
    result_type = None ;receive = '' ;result_count = 0 ;result_sum = 0
    formd.usermaild.choices = [(v.email) for v in NocMail.query.all()]
    print(len(formd.usermaild.choices))
    if formd.usermaild.choices:
        if request.method=='POST' and formd.validate_on_submit():
            maild = NocMail.query.filter_by(email=formd.usermaild.data).first()
            emailDB = Emailmodule()
            print(maild.email)
            receive = emailDB.server_imap4(maild.email,maild.password,maild.serveraddress,maild.port)
            result_type = type(receive)
            result_count = receive.count('\n')
            result_sum = len(receive)
            flash('选定账户:{:}'.format(maild.email))
        else:
            maild = NocMail.query.filter_by(email=formd.usermaild.choices[0]).first()
            emailDB = Emailmodule()
            print(maild.email)
            receive = emailDB.server_imap4(maild.email,maild.password,maild.serveraddress,maild.port)
            result_type = type(receive)
            result_count = receive.count('\n')
            result_sum = len(receive)
            flash('选定账户:{:}'.format(maild.email))
    else:
        return redirect(url_for('core.nocsetting_email'))
    return render_template('nocsetting.html',formd=formd,result_type=result_type,
                            receive=receive,result_count=result_count,result_sum=result_sum)

@core.route('/nocsetting_email',methods=['GET','POST'])
def nocsetting_email():
    form = MailForm()
    if form.validate_on_submit():
        user = form.usermail.data;passwd = form.password.data;server = form.serveraddr.data;port = form.port.data
        nocmail = NocMail(email=user,password=passwd,serveraddress=server,port=port)
        dbmail = NocMail.query.filter_by(email=user).count()
        if dbmail == 0:
            db.session.add(nocmail)
            db.session.commit()
            flash("提交成功")
        else:
            flash('账户已经存在！')
        return redirect(url_for('core.nocsetting_email'))
    return render_template('nocsetting_email.html',form=form,flash=flash)

project/network/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from project import db
from .sshp import Ssh,Ssh_rs
from .forms import SshxForm,ProxyForm,TestForm
from project.models import Proxy

network = Blueprint("network",__name__)

@network.route("/sshx",methods=['GET','POST'])
def sshx():
    form = SshxForm()
    echo = None
    n = 0
    if form.validate_on_submit():
        ip = form.address.data
        port = form.port.data
        username = form.username.data
        password = form.password.data
        command = form.command.data
        ssh = Ssh(ip,port,username,password,command)
        echo = ssh.result()
        n = echo.count('\n')
    return render_template('remote_server.html',form=form,echo=echo,n=n)

@network.route("/sshx_rs",methods=['GET','POST'])
def sshx_rs():
    form = SshxForm()
    echo = None
    n = 0
    if form.validate_on_submit():
        ip = form.address.data
        port = form.port.data
        username = form.username.data
        password = form.password.data
        command = form.command.data
        ssh = Ssh_rs(ip,port,username,password,command)
        echo = ssh.result()
        echo = echo.decode('utf8')
        n = echo.count('\n')
    return render_template('remote_rssw.html',form=form,echo=echo,n=n)

@network.route("/proxy",methods=['GET','POST'])
def proxy():
    form = ProxyForm()
    if form.validate_on_submit():
        data_count = Proxy.query.filter_by(address=form.address.data).count()
        if data_count == 0:
            proxys = Proxy(remarks=form.remarks.data,
                           address=form.address.data,
                           port=form.port.data,
                           username = form.username.data,
                           password = form.password.data)
            db.session.add(proxys)
            db.session.commit()
            flash("success!")
        else:
            pass
    resultall = Proxy.query.all()
    n = len(resultall)
    return render_template('add_proxy.html',form=form,resultall=resultall,n=n)

@network.route('/tracert',methods=['GET','POST'])
def tracert():
    form = TestForm()
    form.address.choices = [(v.address,v.remarks) for v in Proxy.query.all()]
    proxy = None
    echo = None
    n = 0
    if request.method=='POST' and form.validate_on_submit():
        commands = 'mtr -n -r ' + form.proxyid.data
        proxy = Proxy.query.filter_by(address=form.address.data).first()
        ssh = Ssh(proxy.address,proxy.port,proxy.username,proxy.password,commands)
        echo = ssh.result()
        n = echo.count('\n')
    return render_template('route_tracert.html',form=form,echo=echo,n=n)

project/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from project import db
from project.models import User
from project.users.forms import RegistrationForm,LoginForm,UpdateUserForm
from project.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)
db.create_all()

# register
@users.route('/register',methods=['GET','POST'])

def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        if not User.query.filter_by(email=form.email.data).first() and\
            not User.query.filter_by(email=form.username.data).first():
            user = User(email=form.email.data,
                        username=form.username.data,
                        password=form.password.data)
            db.session.add(user)
            db.session.commit()
            flash('注册成功！')
            return redirect(url_for('users.register'))
            
        else:
            flash('用户已经存在！')
            return redirect(url_for('users.register'))
    return render_template('register.html',form=form)



# login
@users.route('/login',methods=['GET','POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if user.check_password(form.password.data) and user is not None:
                login_user(user)
                flash('登录成功')
                next = request.args.get('next')
                if next ==None or not next[0]=='/':
                    next = url_for('core.index')
                return redirect(next)
    return render_template('login.html',form=form)


# logout
@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("core.index"))


# account (update UserForm)
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateUserForm()
    if form.validate_on_submit():
        if form.picture.data:
            username = current_user.username
            pic = add_profile_pic(form.picture.data,username)
            current_user.profile_image = pic
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('User Account Updated')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_image = url_for('static', filename='profile_pics/' + current_user.profile_image)
    return render_template('account.html', profile_image=profile_image, form=form)

project/templates/account.html
{% extends "base.html" %}
{% block content %}

<div>
  <div align='center'>
    <h1 >个人信息</h1>
    <img align='center' src="{{ url_for('static', filename='profile_pics/' + current_user.profile_image) }}">
    <p>{{ current_user.email }}</p>
  </div>
</div>
<div class="container">
  <form  method="POST" action="" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="form-group">
      <!-- {{ form.username.label(class="form-group") }} -->
      {{form.username(class='form-control')  }}
    </div>
    <div class="form-group">
      <!-- {{ form.email.label(class="form-group") }} -->
      {{form.email(class='form-control')  }}
    </div>
    <div class="form-group">
      {{ form.picture.label()}} <br>
      {{ form.picture() }}
    </div>
    <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
  </form>

</div>

{% endblock content %}

project/templates/add_proxy.html
{% extends 'base.html' %}
{% block content %}
<br>
<span class="badge badge-danger">添加代理主机</span><br><br>


<strong>代理主机列表：</strong>
<br><br>
<ol>
    {% for i in range(0,n)%}
        <li>{{resultall[i]}}</li>
    {% endfor %}
</ol>

<form method="POST">
    {{form.hidden_tag()}}
    {{form.remarks.label}}{{form.remarks(class='form-control')}}
    {{form.address.label}}{{form.address(class='form-control')}}
    {{form.port.label}}{{form.port(class='form-control')}}
    {{form.username.label}}{{form.username(class='form-control')}}
    {{form.password.label}}{{form.password(class='form-control')}}
    <br>
    <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
  </form>
{% endblock %}

project/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.min.css')}}" >
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}" >
    <script src="{{url_for('static',filename='js/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/jquery.slim.min.js')}}"></script>
    <script src="{{url_for('static',filename='js/popper.min.js')}}"></script>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body> 
    <ul class='nav'>
      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">首页</a>
      </li>
      {% if current_user.is_authenticated %}
      <li class='nav-link'><a href="{{url_for('users.logout')}}">退出</a></li>
      <li class='nav-link'><a href="{{url_for('users.account')}}">我的账户</a></li>
      <li class='nav-link'><a href="{{url_for('network.sshx')}}">远程服务器</a></li>
      <li class='nav-link'><a href="{{url_for('network.sshx_rs')}}">远程路由交换</a></li>
      <li class='nav-link'><a href="{{url_for('network.proxy')}}">添加代理主机</a></li>
      <li class='nav-link'><a href="{{url_for('network.tracert')}}">路由跟踪测试</a></li>
      <li class='nav-link'><a href="{{url_for('core.croom')}}">IDC管理</a></li>
      <li class='nav-link'><a href="{{url_for('core.nocsetting')}}">设置监控邮箱</a></li>
      {% else %}
      <li class='nav-link'><a href="{{url_for('users.login')}}">登录</a></li>
      <li class='nav-link'><a href="{{url_for('users.register')}}">注册</a></li> 
      {% endif %}
    </ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>
</body>
</html>

project/templates/croom.html
{% extends "base.html" %}
{% block content %}
<br>

<strong>
<h7>当前({{crsum|count}})个机房：{% for i in crsum %}
    【{{i}}】
    {% endfor %}</h7>
<h7>（{{device_count}})台设备</h7></strong>

<br><br>
<!--xlsx开始-->
<table width="1200"  border="1" cellpadding="10">
    <tr>
        <th width="10%" bgcolor="">{{xlsdb_columns[1]}}</th>
        <th width="10%" bgcolor="#20c997">{{xlsdb_columns[3]}}</th>
        <th width="10%" bgcolor="#20c997">{{xlsdb_columns[5]}}</th>
        <th width="10%" bgcolor="#20c997">{{xlsdb_columns[6]}}</th>
        <th width="10%" bgcolor="#20c997">{{xlsdb_columns[9]}}</th>
        <th width="10%" bgcolor="#20c997">{{xlsdb_columns[10]}}</th>
        <th width="40%" bgcolor="#20c997">{{xlsdb_columns[11]}}</th>
    </tr>
{% for i in range(0,device_count) %}
    <tr>
        <td width="10%"><a href="#">{{readxls[i][1]}}</a></td>
        <td width="10%">{{readxls[i][3]}}</td>
        <td width="10%"><a href="{{url_for('core.croompage',mangeip=readxls[i][5],crdev=i)}}">{{readxls[i][5]}}</a></td>
        <td width="10%">{{readxls[i][6]}}</td>
        <td width="10%">{{readxls[i][9]}}</td>
        <td width="10%">{{readxls[i][10]}}</td>
        <td width="40%">{{readxls[i][11]}}</td>
    </tr>
{% endfor %}
</table>
    <!--xlsx结束-->
{% endblock %}

project/templates/croompage.html
{% extends "base.html" %}
{% block content %}
<br>
<a id="cssfr" href="{{url_for('core.croom')}}">返回</a>
<ul>
{% for c in range(0,xlsdb_columns|count) %}
    <li>{{xlsdb_columns[c]}}&nbsp;:&nbsp;<font color="red">{{readxls[crdev][c]}}</font></li>
{% endfor %}
</ul>
{% endblock %}

project/templates/index.html
{% extends 'base.html' %}
{% block content %}
<br>
{% for message in get_flashed_messages() %}
    <div class="alert alert-success">{{ message }}</div>
{% endfor %}

{% endblock %}

project/templates/login.html
{% extends "base.html" %}
{% block content %}

  <form method="POST">
    {{form.hidden_tag()}}
    <br>
    <div class="col-5">{{form.email.label(class="form-group")}} {{form.email(class='form-control')}}</div>
    <br>
    <div class="col-5">{{form.password.label(class="form-group")}} {{form.password(class='form-control')}}</div>
    <br>
    <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
  </form>
{% endblock %}

project/templates/nocsetting.html
{% extends 'base.html' %}
{% block content %}
<br>
<strong><h7><a style="float: right;" href="{{url_for('core.nocsetting_email')}}">添加邮箱</a></h7></strong>
<br>
{% for message in get_flashed_messages() %}
    <div class="alert alert-primary">{{ message }}</div>
{% endfor %}
<br>
<div>
    <form method='POST'>
        {{formd.csrf_token}}
        {{formd.hidden_tag()}}
        <div class="col-5">{{formd.usermaild(class='form-control')}}</div><br>
        <div class="form-group"> {{ formd.submit(class="btn btn-primary") }}</div>
    </form>
</div>

<div class="jumbotron">
    <h7>{{result_type}}-{{result_count}}-{{result_sum}}字</h7>
    <ul>

        {% if '<html>' not in receive  %}
            {% if result_count <= 0 %}
                <h5>#12</h5>
                <li>{{receive}}</li>
            {% else %}
            <h5>#15</h5>
            {% for i in range(0,result_count+1)%}
                <li>{{receive.splitlines()[i]}}</li>
            {% endfor %}
            {% endif %}

        {% else %}
            <h5>#22</h5>
            {{receive}}
        {% endif %}
    </ul>
</div>

{% endblock %}

project/templates/nocsetting_email.html
{% extends 'base.html' %}

{% block content %}
<br>

<a id="cssfr" href="{{url_for('core.nocsetting')}}">返回</a>

<div>
    <form method='POST'>
        {{form.csrf_token}}
        {{form.hidden_tag()}}
        <div class="col-5">{{form.usermail.label}}{{form.usermail(class='form-control')}}</div>
        <div class="col-5">{{form.password.label}}{{form.password(class='form-control')}}</div>
        <div class="col-5">{{form.serveraddr.label}}{{form.serveraddr(class='form-control')}}</div>
        <div class="col-5">{{form.port.label}}{{form.port(class='form-control')}}</div><br>
        <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
    </form>
</div>


{% for message in get_flashed_messages() %}
    <div class="alert alert-danger">{{ message }}</div>
{% endfor %}

{% endblock %}

project/templates/register.html
{% extends "base.html" %}
{% block content %}

{% for message in get_flashed_messages() %}
    <div class="alert alert-success">{{ message }}</div>
{% endfor %}

  <form method="POST">
    {{form.hidden_tag()}}
    <br>
    <div class="col-5">{{form.email.label(class="form-group")}} {{form.email(class='form-control')}}</div>
    <br>
    <div class="col-5">{{form.username.label(class="form-group")}}{{form.username(class='form-control')}}</div>
    <br>
    <div class="col-5">{{form.password.label(class="form-group")}}{{form.password(class='form-control')}}</div>
    <br>
    <div class="col-5">{{form.pass_confirm.label(class="form-group")}}{{form.pass_confirm(class='form-control')}}</div>
    <br>
    <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
  </form>

  {{emaild}}
{% endblock %}

project/templates/remote_rssw.html
{% extends 'base.html' %}
{% block content %}
<br>
<span class="badge badge-danger">交换机SSH远程管理</span><br><br>
  <div>
    <form method="post">
      {{form.hidden_tag()}}
      <div class="col-3">{{form.address(class='form-control',placeholder='IP地址')}}</div><br>
      <div class="col-3">{{form.port(class='form-control',placeholder='端口')}}</div><br>
      <div class="col-3">{{form.username(class='form-control',placeholder='用户名')}}</div><br>
      <div class="col-3">{{form.password(class='form-control',placeholder='密码')}}</div><br>
      <div class="col-7">{{form.command(class='form-control',placeholder='指令')}}</div><br>
      <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
    </form>
  </div>
  <br>
  <div class="jumbotron">
    <ol>
      {% for i in range(0,n)%}
        <li>{{echo.splitlines()[i]}}</li>
      {% endfor %}
    </ol>
  </div>
{% endblock %}

project/templates/remote_server.html
{% extends 'base.html' %}
{% block content %}
<br>
<span class="badge badge-danger">Linux远程管理</span><br><br>

  <div>
    <form method="post">
      {{form.hidden_tag()}}
      <div class="col-3">{{form.address(class='form-control',placeholder='IP地址')}}</div><br>
      <div class="col-3">{{form.port(class='form-control',placeholder='端口')}}</div><br>
      <div class="col-3">{{form.username(class='form-control',placeholder='用户名')}}</div><br>
      <div class="col-3">{{form.password(class='form-control',placeholder='密码')}}</div><br>
      <div class="col-7">{{form.command(class='form-control',placeholder='指令')}}</div><br>
      <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
    </form>
  </div>
  <br>
  <div class="jumbotron">
    <ol>
        {% for i in range(0,n)%}
            <li>{{echo.splitlines()[i]}}</li>
        {% endfor %}
    </ol>
  </div>
{% endblock %}

project/templates/route_tracert.html
{% extends 'base.html' %}
{% block content %}
<br>
<span class="badge badge-danger">路由MTR测试</span><br><br>

<div>
    <form method="post">
      {{form.hidden_tag()}}
      <div class="col-3">{{form.address(class='form-control')}}</div><br>
      <div class="col-3">{{form.proxyid(class='form-control',placeholder='IPv4')}}</div><br>
      <div class="form-group"> {{ form.submit(class="btn btn-primary") }}</div>
    </form>
</div>

<div class="jumbotron">
    <ol>
      {% for i in range(0,n)%}
        <li>{{echo.splitlines()[i]}}</li>
      {% endfor %}
    </ol>
</div>
{% endblock %}